<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\T3.CallDevices\T3.CallDevices.csproj" />
    <ProjectReference Include="..\T3ACS.Model\T3ACS.Model.csproj" />
  </ItemGroup>

</Project>