<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\T3ACS.Model\T3ACS.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
